
export default function StartPage() {
  return (
    <div className="d-flex justify-content-center align-items-center flex-column h-100">
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
      <h1>START</h1>
    </div>
  )
}
